INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Português', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Espanhol', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Inglês', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Francês', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Alemão', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Italiano', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('História', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Geografia', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Matemática', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Química', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Física', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Biologia', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Geologia', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Informática', 'Tecnologia');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Programação', 'Tecnologia');


INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (6, '1º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (7, '2º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (8, '3º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (9, '4º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (10, '5º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (11, '6º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (12, '7º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (13, '8º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (14, '9º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (15, '10º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (16, '11º Ano');
INSERT INTO ESCOLARIDADE (IDADE, ANO_ESCOLAR) VALUES (17, '12º Ano');